services:
  cockroach:
    image: cockroachdb/cockroach:v22.2.3
    command: start-single-node --insecure # keep it an insecure and run multiple nodes later 
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  cockroach-data: