services:
  cockroach:
    image: cockroachdb/cockroach:v22.2.3
    command: start-single-node --insecure # keep it an insecure and run multiple nodes later 
    container_name: my-cockroach
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  job-service:
    build: ./job_service
    environment:
      DB_HOST: cockroachdb
      RABBITMQ_HOST: rabbitmq
    ports:
      - "7000:7000"
    depends_on:
      cockroachdb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  
  scheduler:
    build: ./scheduler
    environment:
      DB_HOST: cockroachdb
      RABBITMQ_HOST: rabbitmq
    depends_on:
      cockroachdb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  
  worker:
    build: ./worker
    environment:
      DB_HOST: cockroachdb
      RABBITMQ_HOST: rabbitmq
    depends_on:
      cockroachdb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 5
    
volumes:
  cockroach-data: