spring.application.name=job_service
spring.port=7000
spring.datasource.url=jdbc:postgresql://localhost:26257/dist_jobs_scheduler?sslmode=disable
spring.datasource.useqrname=root
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver