spring.application.name=job_service
server.port=7000

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:26257/dist_jobs_scheduler?sslmode=disable
spring.datasource.username=root
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=10