spring.application.name=scheduler
server.port=60000

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:26257/dist_jobs_scheduler?sslmode=disable
spring.datasource.useqrname=root
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=10d